# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'TV_Discovery' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TV_Discovery
  pod 'SwiftyJSON'
  pod 'SDWebImage', '~>3.8'

end

workspace ‘TV_Discovery.xcworkspace’
